[all]
master ansible_host=111.88.247.163 ip=10.10.0.18
node1  ansible_host=111.88.247.240 ip=10.10.0.19
node2  ansible_host=111.88.153.68 ip=10.20.0.31
node3  ansible_host=81.26.180.156  ip=10.30.0.7

[kube_control_plane]
master

[etcd]
master

[kube_node]
node1
node2
node3

[k8s_cluster:children]
kube_control_plane
kube_node
