name: CI/CD Pipeline (Release + Deploy)

on:
  push:
    tags:
      - "v*"

jobs:

  # 1. Checkout
  checkout:
    name: 01 - Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


  # 2. Extract version
  version:
    name: 02 - Extract Version
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      version: ${{ steps.setver.outputs.version }}

    steps:
      - name: Set version
        id: setver
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT


  # 3. Build image
  build:
    name: 03 - Build Image
    runs-on: ubuntu-latest
    needs: version

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ needs.version.outputs.version }} ./diplom/test-app


  # 4. Push image
  push:
    name: 04 - Push Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ needs.version.outputs.version }}


  # 5. Deploy via Bastion -> Master -> Kubernetes
  deploy:
    name: 05 - Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Deploy via Bastion SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}   # bastion IP
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            VERSION=${GITHUB_REF#refs/tags/}

            echo "Deploying version: $VERSION"

            ssh ubuntu@10.10.0.3 << EOF

            kubectl set image deployment/nginx-image \
              nginx-image=${{ secrets.DOCKER_USERNAME }}/app:$VERSION

            kubectl rollout status deployment/nginx-image

            kubectl get pods
            kubectl get svc

            EOF


  # 6. Verify (on bastion)
  verify:
    name: 06 - Verify Deployment
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: SSH verify cluster via bastion
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "=== NODES ==="
            ssh ubuntu@10.10.0.3 "kubectl get nodes -o wide"

            echo "=== PODS ==="
            ssh ubuntu@10.10.0.3 "kubectl get pods"

            echo "=== SERVICES ==="
            ssh ubuntu@10.10.0.3 "kubectl get svc"

            echo "=== DEPLOYMENT STATUS ==="
            ssh ubuntu@10.10.0.3 "kubectl rollout status deployment/nginx-image"