name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  terraform:
    name: Terraform Check (${{ matrix.dir }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir:
          - diplom/infra/01-bootstrap
          - diplom/infra/02-network
          - diplom/infra/03-k8s

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ matrix.dir }}
        run: terraform init -backend=false

      - name: Terraform Format Check
        working-directory: ${{ matrix.dir }}
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ${{ matrix.dir }}
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ${{ matrix.dir }}
        run: terraform plan -no-color